// <auto-generated />
using System;
using System.Collections.Generic;
using Harlok.VendingMachine.Domain.Primitives;
using Harlok.VendingMachine.Infrastructure.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Harlok.VendingMachine.Infrastructure.Migrations
{
    [DbContext(typeof(VendingMachineContext))]
    [Migration("20240429194458_ChangeVendingMachine")]
    partial class ChangeVendingMachine
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Harlok.VendingMachine.Domain.Entities.Drink", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<short>("Amount")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PictureUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("picture_url");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(7, 2)")
                        .HasColumnName("price");

                    b.Property<long?>("VendingMachineId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("drink_pkey");

                    b.HasIndex("VendingMachineId");

                    b.ToTable("drink", (string)null);
                });

            modelBuilder.Entity("Harlok.VendingMachine.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UUID")
                        .HasColumnName("id");

                    b.Property<IReadOnlyCollection<Coin>>("Coins")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("coins");

                    b.HasKey("Id")
                        .HasName("user_pkey");

                    b.ToTable("user", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6c33c97a-92de-4e5b-b473-85f5f185f4a8"),
                            Coins = new List<Coin>()
                        });
                });

            modelBuilder.Entity("Harlok.VendingMachine.Domain.Entities.VendingMachine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<IReadOnlyCollection<Coin>>("Deposit")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("deposit");

                    b.Property<decimal>("EarnedMoney")
                        .HasColumnType("numeric(7, 2)")
                        .HasColumnName("earned_money");

                    b.HasKey("Id")
                        .HasName("vending_machine_pkey");

                    b.ToTable("vending_machine", (string)null);
                });

            modelBuilder.Entity("Harlok.VendingMachine.Domain.Entities.Drink", b =>
                {
                    b.HasOne("Harlok.VendingMachine.Domain.Entities.VendingMachine", null)
                        .WithMany("Drinks")
                        .HasForeignKey("VendingMachineId");
                });

            modelBuilder.Entity("Harlok.VendingMachine.Domain.Entities.VendingMachine", b =>
                {
                    b.Navigation("Drinks");
                });
#pragma warning restore 612, 618
        }
    }
}
